from exceptions.base import RESTpyException

class RESTpyAuthException(RESTpyException):
    base_message = "Auth error"

